pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                bat 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                bat 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                bat  './jenkins/scripts/deliver.bat'
            }
        }
        stage('Finish') {
            steps {
               echo 'The Job Name is Renamed to Finish'
            }
        }
    }
}
